FROM docker.io/rust:1.79 as builder
WORKDIR /app
COPY ../Cargo.toml ./
COPY ../../common ./common
COPY . ./backtest_svc
RUN cargo build --release -p backtest_svc

FROM docker.io/debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/backtest_svc /usr/local/bin/backtest_svc
ENV RUST_LOG=backtest_svc=info
EXPOSE 8081
CMD ["/usr/local/bin/backtest_svc"]
