FROM docker.io/rust:1.79 as builder
WORKDIR /app
COPY ../Cargo.toml ../rust-toolchain.toml ./
COPY ../../common ./common
COPY . ./api
RUN cargo build --release -p api

FROM docker.io/debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/api /usr/local/bin/api
ENV RUST_LOG=api=info
EXPOSE 8080
CMD ["/usr/local/bin/api"]
