FROM docker.io/rust:1.79 as builder
WORKDIR /app
COPY ../Cargo.toml ./
COPY ../common ./common
COPY . ./portfolio_svc
RUN cargo build --release -p portfolio_svc

FROM docker.io/debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/portfolio_svc /usr/local/bin/portfolio_svc
ENV RUST_LOG=portfolio_svc=info
EXPOSE 8082
CMD ["/usr/local/bin/portfolio_svc"]
