[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13.1"
tokio = { version = "1", features = ["full"] }
prost = "0.14.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
